// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     chzcake:metadata@1.0.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
	"wit_component/export_chzcake_metadata_metadata"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (6 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport chzcake:metadata/metadata@1.0.0#get
func wasm_export_chzcake_metadata_metadata_get() uintptr {

	pinner := &syncExportPinner
	result := export_chzcake_metadata_metadata.Get()
	utf8 := unsafe.Pointer(unsafe.StringData((result).Name))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len((result).Name)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData((result).Version))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((result).Version)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	utf81 := unsafe.Pointer(unsafe.StringData((result).Description))
	pinner.Pin(utf81)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uint32(len((result).Description)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uintptr(uintptr(utf81)))
	return exportReturnArea

}

//go:wasmexport cabi_post_chzcake:metadata/metadata@1.0.0#get
func wasm_export_post_return_chzcake_metadata_metadata_get(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
