// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-25T22:48:10+03:00
// RPL version: 0.7.3
// Author: <rpl>
package token

import (
	typespkg "github.com/rp1s/chzcake/internal/parser/token/types"
)

// TokenKind переэкспортирует shared RPL enum `TokenKind`.
type TokenKind = typespkg.TokenKind

const TokenKindINVALID = typespkg.TokenKindINVALID

const TokenKindLINE_COMMENT = typespkg.TokenKindLINE_COMMENT

const TokenKindBLOCK_COMMENT = typespkg.TokenKindBLOCK_COMMENT

const TokenKindWHITESPACE = typespkg.TokenKindWHITESPACE

const TokenKindEND_OF_FILE = typespkg.TokenKindEND_OF_FILE

const TokenKindINTEGER_LITERAL = typespkg.TokenKindINTEGER_LITERAL

const TokenKindIMAGINARY_LITERAL = typespkg.TokenKindIMAGINARY_LITERAL

const TokenKindFLOAT_LITERAL = typespkg.TokenKindFLOAT_LITERAL

const TokenKindSTRING_LITERAL = typespkg.TokenKindSTRING_LITERAL

const TokenKindRAW_STRING_LITERAL = typespkg.TokenKindRAW_STRING_LITERAL

const TokenKindCHARACTER_LITERAL = typespkg.TokenKindCHARACTER_LITERAL

const TokenKindIDENTIFIER = typespkg.TokenKindIDENTIFIER

const TokenKindTRUE = typespkg.TokenKindTRUE

const TokenKindFALSE = typespkg.TokenKindFALSE

const TokenKindNULL = typespkg.TokenKindNULL

const TokenKindTHIS = typespkg.TokenKindTHIS

const TokenKindMAP = typespkg.TokenKindMAP

const TokenKindPACKAGE = typespkg.TokenKindPACKAGE

const TokenKindUSE = typespkg.TokenKindUSE

const TokenKindIMPORT = typespkg.TokenKindIMPORT

const TokenKindAS = typespkg.TokenKindAS

const TokenKindPUB = typespkg.TokenKindPUB

const TokenKindLET = typespkg.TokenKindLET

const TokenKindASSIGN = typespkg.TokenKindASSIGN

const TokenKindRIGHT_ARROW = typespkg.TokenKindRIGHT_ARROW

const TokenKindLEFT_ARROW = typespkg.TokenKindLEFT_ARROW

const TokenKindMINUS = typespkg.TokenKindMINUS

const TokenKindPLUS = typespkg.TokenKindPLUS

const TokenKindSTAR = typespkg.TokenKindSTAR

const TokenKindSLASH = typespkg.TokenKindSLASH

const TokenKindPERCENT = typespkg.TokenKindPERCENT

const TokenKindCARET = typespkg.TokenKindCARET

const TokenKindATTRIBUTE_START = typespkg.TokenKindATTRIBUTE_START

const TokenKindATTRIBUTE_END = typespkg.TokenKindATTRIBUTE_END

const TokenKindTEMPLATE_START = typespkg.TokenKindTEMPLATE_START

const TokenKindTEMPLATE_END = typespkg.TokenKindTEMPLATE_END

const TokenKindAMPERSAND = typespkg.TokenKindAMPERSAND

const TokenKindLEFT_PAREN = typespkg.TokenKindLEFT_PAREN

const TokenKindRIGHT_PAREN = typespkg.TokenKindRIGHT_PAREN

const TokenKindLEFT_BRACE = typespkg.TokenKindLEFT_BRACE

const TokenKindRIGHT_BRACE = typespkg.TokenKindRIGHT_BRACE

const TokenKindLEFT_BRACKET = typespkg.TokenKindLEFT_BRACKET

const TokenKindRIGHT_BRACKET = typespkg.TokenKindRIGHT_BRACKET

const TokenKindCOLON = typespkg.TokenKindCOLON

const TokenKindDOUBLE_COLON = typespkg.TokenKindDOUBLE_COLON

const TokenKindDOT = typespkg.TokenKindDOT

const TokenKindCOMMA = typespkg.TokenKindCOMMA

var TokenKindValues = typespkg.TokenKindValues

var ParseTokenKind = typespkg.ParseTokenKind
