// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-25T22:48:10+03:00
// RPL version: 0.7.3
// Author: <rpl>
package types

import (
	"fmt"
)

// TokenKind — uint-backed enum, объявленный в RPL.
type TokenKind uint

const (
	TokenKindINVALID TokenKind = iota
	TokenKindLINE_COMMENT
	TokenKindBLOCK_COMMENT
	TokenKindWHITESPACE
	TokenKindEND_OF_FILE
	TokenKindINTEGER_LITERAL
	TokenKindIMAGINARY_LITERAL
	TokenKindFLOAT_LITERAL
	TokenKindSTRING_LITERAL
	TokenKindRAW_STRING_LITERAL
	TokenKindCHARACTER_LITERAL
	TokenKindIDENTIFIER
	TokenKindTRUE
	TokenKindFALSE
	TokenKindNULL
	TokenKindTHIS
	TokenKindMAP
	TokenKindPACKAGE
	TokenKindUSE
	TokenKindIMPORT
	TokenKindAS
	TokenKindPUB
	TokenKindLET
	TokenKindASSIGN
	TokenKindRIGHT_ARROW
	TokenKindLEFT_ARROW
	TokenKindMINUS
	TokenKindPLUS
	TokenKindSTAR
	TokenKindSLASH
	TokenKindPERCENT
	TokenKindCARET
	TokenKindATTRIBUTE_START
	TokenKindATTRIBUTE_END
	TokenKindTEMPLATE_START
	TokenKindTEMPLATE_END
	TokenKindAMPERSAND
	TokenKindLEFT_PAREN
	TokenKindRIGHT_PAREN
	TokenKindLEFT_BRACE
	TokenKindRIGHT_BRACE
	TokenKindLEFT_BRACKET
	TokenKindRIGHT_BRACKET
	TokenKindCOLON
	TokenKindDOUBLE_COLON
	TokenKindDOT
	TokenKindCOMMA
)

// String возвращает имя элемента или его явно заданную строковую подпись.
func (value TokenKind) String() string {
	switch value {
	case TokenKindINVALID:
		return "INVALID"
	case TokenKindLINE_COMMENT:
		return "LINE_COMMENT"
	case TokenKindBLOCK_COMMENT:
		return "BLOCK_COMMENT"
	case TokenKindWHITESPACE:
		return "WHITESPACE"
	case TokenKindEND_OF_FILE:
		return "END_OF_FILE"
	case TokenKindINTEGER_LITERAL:
		return "INTEGER_LITERAL"
	case TokenKindIMAGINARY_LITERAL:
		return "IMAGINARY_LITERAL"
	case TokenKindFLOAT_LITERAL:
		return "FLOAT_LITERAL"
	case TokenKindSTRING_LITERAL:
		return "STRING_LITERAL"
	case TokenKindRAW_STRING_LITERAL:
		return "RAW_STRING_LITERAL"
	case TokenKindCHARACTER_LITERAL:
		return "CHARACTER_LITERAL"
	case TokenKindIDENTIFIER:
		return "IDENTIFIER"
	case TokenKindTRUE:
		return "TRUE"
	case TokenKindFALSE:
		return "FALSE"
	case TokenKindNULL:
		return "NULL"
	case TokenKindTHIS:
		return "THIS"
	case TokenKindMAP:
		return "MAP"
	case TokenKindPACKAGE:
		return "PACKAGE"
	case TokenKindUSE:
		return "USE"
	case TokenKindIMPORT:
		return "IMPORT"
	case TokenKindAS:
		return "AS"
	case TokenKindPUB:
		return "PUB"
	case TokenKindLET:
		return "LET"
	case TokenKindASSIGN:
		return "ASSIGN"
	case TokenKindRIGHT_ARROW:
		return "RIGHT_ARROW"
	case TokenKindLEFT_ARROW:
		return "LEFT_ARROW"
	case TokenKindMINUS:
		return "MINUS"
	case TokenKindPLUS:
		return "PLUS"
	case TokenKindSTAR:
		return "STAR"
	case TokenKindSLASH:
		return "SLASH"
	case TokenKindPERCENT:
		return "PERCENT"
	case TokenKindCARET:
		return "CARET"
	case TokenKindATTRIBUTE_START:
		return "ATTRIBUTE_START"
	case TokenKindATTRIBUTE_END:
		return "ATTRIBUTE_END"
	case TokenKindTEMPLATE_START:
		return "TEMPLATE_START"
	case TokenKindTEMPLATE_END:
		return "TEMPLATE_END"
	case TokenKindAMPERSAND:
		return "AMPERSAND"
	case TokenKindLEFT_PAREN:
		return "LEFT_PAREN"
	case TokenKindRIGHT_PAREN:
		return "RIGHT_PAREN"
	case TokenKindLEFT_BRACE:
		return "LEFT_BRACE"
	case TokenKindRIGHT_BRACE:
		return "RIGHT_BRACE"
	case TokenKindLEFT_BRACKET:
		return "LEFT_BRACKET"
	case TokenKindRIGHT_BRACKET:
		return "RIGHT_BRACKET"
	case TokenKindCOLON:
		return "COLON"
	case TokenKindDOUBLE_COLON:
		return "DOUBLE_COLON"
	case TokenKindDOT:
		return "DOT"
	case TokenKindCOMMA:
		return "COMMA"
	default:
		return fmt.Sprintf("TokenKind(%d)", uint64(value))
	}
}

// IsValid сообщает, объявлено ли значение в enum TokenKind.
func (value TokenKind) IsValid() bool {
	switch value {
	case TokenKindINVALID, TokenKindLINE_COMMENT, TokenKindBLOCK_COMMENT, TokenKindWHITESPACE, TokenKindEND_OF_FILE, TokenKindINTEGER_LITERAL, TokenKindIMAGINARY_LITERAL, TokenKindFLOAT_LITERAL, TokenKindSTRING_LITERAL, TokenKindRAW_STRING_LITERAL, TokenKindCHARACTER_LITERAL, TokenKindIDENTIFIER, TokenKindTRUE, TokenKindFALSE, TokenKindNULL, TokenKindTHIS, TokenKindMAP, TokenKindPACKAGE, TokenKindUSE, TokenKindIMPORT, TokenKindAS, TokenKindPUB, TokenKindLET, TokenKindASSIGN, TokenKindRIGHT_ARROW, TokenKindLEFT_ARROW, TokenKindMINUS, TokenKindPLUS, TokenKindSTAR, TokenKindSLASH, TokenKindPERCENT, TokenKindCARET, TokenKindATTRIBUTE_START, TokenKindATTRIBUTE_END, TokenKindTEMPLATE_START, TokenKindTEMPLATE_END, TokenKindAMPERSAND, TokenKindLEFT_PAREN, TokenKindRIGHT_PAREN, TokenKindLEFT_BRACE, TokenKindRIGHT_BRACE, TokenKindLEFT_BRACKET, TokenKindRIGHT_BRACKET, TokenKindCOLON, TokenKindDOUBLE_COLON, TokenKindDOT, TokenKindCOMMA:
		return true
	default:
		return false
	}
}

// TokenKindValues возвращает все элементы enum в порядке объявления.
func TokenKindValues() []TokenKind {
	return []TokenKind{TokenKindINVALID, TokenKindLINE_COMMENT, TokenKindBLOCK_COMMENT, TokenKindWHITESPACE, TokenKindEND_OF_FILE, TokenKindINTEGER_LITERAL, TokenKindIMAGINARY_LITERAL, TokenKindFLOAT_LITERAL, TokenKindSTRING_LITERAL, TokenKindRAW_STRING_LITERAL, TokenKindCHARACTER_LITERAL, TokenKindIDENTIFIER, TokenKindTRUE, TokenKindFALSE, TokenKindNULL, TokenKindTHIS, TokenKindMAP, TokenKindPACKAGE, TokenKindUSE, TokenKindIMPORT, TokenKindAS, TokenKindPUB, TokenKindLET, TokenKindASSIGN, TokenKindRIGHT_ARROW, TokenKindLEFT_ARROW, TokenKindMINUS, TokenKindPLUS, TokenKindSTAR, TokenKindSLASH, TokenKindPERCENT, TokenKindCARET, TokenKindATTRIBUTE_START, TokenKindATTRIBUTE_END, TokenKindTEMPLATE_START, TokenKindTEMPLATE_END, TokenKindAMPERSAND, TokenKindLEFT_PAREN, TokenKindRIGHT_PAREN, TokenKindLEFT_BRACE, TokenKindRIGHT_BRACE, TokenKindLEFT_BRACKET, TokenKindRIGHT_BRACKET, TokenKindCOLON, TokenKindDOUBLE_COLON, TokenKindDOT, TokenKindCOMMA}
}

// ParseTokenKind разбирает имя элемента или его строковую подпись.
func ParseTokenKind(text string) (TokenKind, bool) {
	switch text {
	case "INVALID":
		return TokenKindINVALID, true
	case "LINE_COMMENT":
		return TokenKindLINE_COMMENT, true
	case "BLOCK_COMMENT":
		return TokenKindBLOCK_COMMENT, true
	case "WHITESPACE":
		return TokenKindWHITESPACE, true
	case "END_OF_FILE":
		return TokenKindEND_OF_FILE, true
	case "INTEGER_LITERAL":
		return TokenKindINTEGER_LITERAL, true
	case "IMAGINARY_LITERAL":
		return TokenKindIMAGINARY_LITERAL, true
	case "FLOAT_LITERAL":
		return TokenKindFLOAT_LITERAL, true
	case "STRING_LITERAL":
		return TokenKindSTRING_LITERAL, true
	case "RAW_STRING_LITERAL":
		return TokenKindRAW_STRING_LITERAL, true
	case "CHARACTER_LITERAL":
		return TokenKindCHARACTER_LITERAL, true
	case "IDENTIFIER":
		return TokenKindIDENTIFIER, true
	case "TRUE":
		return TokenKindTRUE, true
	case "FALSE":
		return TokenKindFALSE, true
	case "NULL":
		return TokenKindNULL, true
	case "THIS":
		return TokenKindTHIS, true
	case "MAP":
		return TokenKindMAP, true
	case "PACKAGE":
		return TokenKindPACKAGE, true
	case "USE":
		return TokenKindUSE, true
	case "IMPORT":
		return TokenKindIMPORT, true
	case "AS":
		return TokenKindAS, true
	case "PUB":
		return TokenKindPUB, true
	case "LET":
		return TokenKindLET, true
	case "ASSIGN":
		return TokenKindASSIGN, true
	case "RIGHT_ARROW":
		return TokenKindRIGHT_ARROW, true
	case "LEFT_ARROW":
		return TokenKindLEFT_ARROW, true
	case "MINUS":
		return TokenKindMINUS, true
	case "PLUS":
		return TokenKindPLUS, true
	case "STAR":
		return TokenKindSTAR, true
	case "SLASH":
		return TokenKindSLASH, true
	case "PERCENT":
		return TokenKindPERCENT, true
	case "CARET":
		return TokenKindCARET, true
	case "ATTRIBUTE_START":
		return TokenKindATTRIBUTE_START, true
	case "ATTRIBUTE_END":
		return TokenKindATTRIBUTE_END, true
	case "TEMPLATE_START":
		return TokenKindTEMPLATE_START, true
	case "TEMPLATE_END":
		return TokenKindTEMPLATE_END, true
	case "AMPERSAND":
		return TokenKindAMPERSAND, true
	case "LEFT_PAREN":
		return TokenKindLEFT_PAREN, true
	case "RIGHT_PAREN":
		return TokenKindRIGHT_PAREN, true
	case "LEFT_BRACE":
		return TokenKindLEFT_BRACE, true
	case "RIGHT_BRACE":
		return TokenKindRIGHT_BRACE, true
	case "LEFT_BRACKET":
		return TokenKindLEFT_BRACKET, true
	case "RIGHT_BRACKET":
		return TokenKindRIGHT_BRACKET, true
	case "COLON":
		return TokenKindCOLON, true
	case "DOUBLE_COLON":
		return TokenKindDOUBLE_COLON, true
	case "DOT":
		return TokenKindDOT, true
	case "COMMA":
		return TokenKindCOMMA, true
	default:
		return 0, false
	}
}
