// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     chzcake:metadata@1.0.0

package chzcake_metadata_metadata

import ()

type Info struct {
	Name        string
	Version     string
	Description string
}
