// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-25T22:48:10+03:00
// RPL version: 0.7.3
// Author: <rpl>
package position

// Position описывает сгенерированную модель данных.
type Position struct {
	FileName string
	Line     uint64
	Column   uint64
	Offset   uint64
}
